CFLAGS=-Wall -g

# all为makefile的默认目标，输入make自动执行
all: ex1

# 生成ex1需要源文件ex1.c
ex1: ex1.c
	cc -Wall -g ex1.c -o ex1

clean:
	rm -f ex1


hello:
	echo "Hello, World"
	echo "This line will print if the file hello does not exist"

# targets: prerequisites
# 	command
# 	command
# 	command


# Variables can only be strings
